services:
  - type: static
    name: flipbook
    env: static
    buildCommand: |
      python main.py
    staticPublishPath: output
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 