services:
  - type: web
    name: flipbook
    env: static
    buildCommand: python main.py
    staticPublishPath: output
    routes:
      - type: rewrite
        source: /*
        destination: /flipbook.html 