services:
  - type: web
    name: kcc-flipbook
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y poppler-utils
      pip install -r requirements.txt
      python main.py
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 --access-logfile - --error-logfile - wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
    autoDeploy: true
    healthCheckPath: /
    domains:
      - kcc-flipbook.onrender.com
