services:
  - type: web
    name: flipbook-8hfy
    env: static
    buildCommand: |
      apt-get update
      apt-get install -y poppler-utils
      export PATH="/usr/bin:$PATH"
      pip install pdf2image
      pip install Pillow
      python main.py
    staticPublishPath: ./output
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: PATH
        value: "/usr/bin:$PATH"
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /flipbook.html 