services:
  - type: web
    name: flipbook-8hfy
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y poppler-utils
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python main.py
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 10000
    healthCheckPath: /flipbook.html
    staticPublishPath: ./output
