services:
  - type: static
    name: flipbook-8hfy
    staticPublishPath: ./output
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /flipbook.html
